SYMFLUENCE_DATA_DIR: /Users/darrieythorsson/compHydro/code/SYMFLUENCE_data
SYMFLUENCE_CODE_DIR: /Users/darrieythorsson/compHydro/code/SYMFLUENCE
MPI_PROCESSES: 1
DEBUG_MODE: false
LOG_LEVEL: INFO
LOG_TO_FILE: true
LOG_FORMAT: detailed
FORCE_RUN_ALL_STEPS: false
USE_LOCAL_SCRATCH: false
STOP_ON_ERROR: true
DOMAIN_NAME: Dalalven River
EXPERIMENT_ID: pour_point_setup
EXPERIMENT_TIME_START: 2004-01-01 01:00
EXPERIMENT_TIME_END: 2004-01-31 23:00
CALIBRATION_PERIOD: 2004-01-05, 2004-01-19
EVALUATION_PERIOD: 2004-01-20, 2004-01-30
SPINUP_PERIOD: 2004-01-01, 2004-01-04
DOMAIN_DEFINITION_METHOD: delineate
DOMAIN_DISCRETIZATION: GRUs
GRID_CELL_SIZE: 1000.0
CLIP_GRID_TO_WATERSHED: true
POUR_POINT_COORDS: 60.6333/17.0667
BOUNDING_BOX_COORDS: 61.1333/16.5667/60.1333/17.5667
ROUTING_DELINEATION: lumped
GEOFABRIC_TYPE: na
DELINEATION_METHOD: stream_threshold
CURVATURE_THRESHOLD: 0.0
MIN_SOURCE_THRESHOLD: 100
STREAM_THRESHOLD: 5000.0
SLOPE_AREA_THRESHOLD: 100.0
SLOPE_AREA_EXPONENT: 2.0
AREA_EXPONENT: 1.0
MULTI_SCALE_THRESHOLDS: 10000,5000,2500,1000,500
USE_DROP_ANALYSIS: false
DROP_ANALYSIS_MIN_THRESHOLD: 100
DROP_ANALYSIS_MAX_THRESHOLD: 10000
DROP_ANALYSIS_NUM_THRESHOLDS: 10
DROP_ANALYSIS_LOG_SPACING: true
LUMPED_WATERSHED_METHOD: TauDEM
CLEANUP_INTERMEDIATE_FILES: false
DELINEATE_COASTAL_WATERSHEDS: false
DELINEATE_BY_POURPOINT: true
MOVE_OUTLETS_MAX_DISTANCE: 200.0
MIN_GRU_SIZE: 0.0
MIN_HRU_SIZE: 4.0
ELEVATION_BAND_SIZE: 200.0
RADIATION_CLASS_NUMBER: 5
ASPECT_CLASS_NUMBER: 8
ASPECT_PATH: default
DATA_ACCESS: cloud
DOWNLOAD_DEM: true
DOWNLOAD_SOIL: true
DOWNLOAD_LAND_COVER: true
DEM_SOURCE: fabdem
LAND_CLASS_SOURCE: modis
LAND_CLASS_NAME: default
FORCE_DOWNLOAD: false
STREAMFLOW_DATA_PROVIDER: WSC
DOWNLOAD_USGS_DATA: false
DOWNLOAD_SMHI_DATA: false
DOWNLOAD_LAMAH_ICE_DATA: false
DOWNLOAD_ISMN: false
DOWNLOAD_GLACIER_DATA: false
ELEV_CHUNK_SIZE: 10000
ELEV_TILE_TARGET: 50000
SOILGRIDS_LAYER: wrb_0-5cm_mode
SOILGRIDS_WCS_MAP: /map/wcs/soilgrids.map
SOILGRIDS_HS_CACHE_DIR: default
SOILGRIDS_HS_RESOURCE_ID: 1361509511e44adfba814f6950c6e742
MODIS_LANDCOVER_BASE_URL: https://zenodo.org/records/8367523/files
MODIS_LANDCOVER_CACHE_DIR: default
NLCD_COVERAGE_ID: NLCD_2019_Land_Cover_L48
FORCING_DATASET: ERA5
FORCING_TIME_STEP_SIZE: 3600
FORCING_VARIABLES: default
FORCING_MEASUREMENT_HEIGHT: 2.0
APPLY_LAPSE_RATE: true
LAPSE_RATE: 0.0065
FORCING_SHAPE_LAT_NAME: lat
FORCING_SHAPE_LON_NAME: lon
PET_METHOD: oudin
SUPPLEMENT_FORCING: false
NEX_MODELS:
- ACCESS-CM2
- GFDL-ESM4
NEX_SCENARIOS:
- historical
NEX_ENSEMBLES:
- r1i1p1f1
NEX_VARIABLES:
- hurs
- huss
- pr
- rlds
- rsds
- sfcWind
- tas
- tasmax
- tasmin
EM_EARTH_PRCP_DIR: /path/to/EM-EARTH/prcp/data
EM_EARTH_TMEAN_DIR: /path/to/EM-EARTH/tmean/data
EM_EARTH_MIN_BBOX_SIZE: 0.1
EM_EARTH_MAX_EXPANSION: 0.2
EM_PRCP: prcp
EM_EARTH_DATA_TYPE: deterministic
ERA5_ZARR_PATH: gcp-public-data-arco-era5/ar/full_37-1h-0p25deg-chunk-1.zarr-v3
ERA5_TIME_STEP_HOURS: 1
HYDROLOGICAL_MODEL: SUMMA
ROUTING_MODEL: mizuRoute
SUMMA_INSTALL_PATH: default
SUMMA_EXE: summa_sundials.exe
SETTINGS_SUMMA_PATH: default
SETTINGS_SUMMA_FILEMANAGER: fileManager.txt
SETTINGS_SUMMA_FORCING_LIST: forcingFileList.txt
SETTINGS_SUMMA_COLDSTATE: coldState.nc
SETTINGS_SUMMA_TRIALPARAMS: trialParams.nc
SETTINGS_SUMMA_ATTRIBUTES: attributes.nc
SETTINGS_SUMMA_OUTPUT: outputControl.txt
SETTINGS_SUMMA_BASIN_PARAMS_FILE: basinParamInfo.txt
SETTINGS_SUMMA_LOCAL_PARAMS_FILE: localParamInfo.txt
SETTINGS_SUMMA_CONNECT_HRUS: true
SETTINGS_SUMMA_TRIALPARAM_N: 0
SETTINGS_SUMMA_USE_PARALLEL_SUMMA: false
SETTINGS_SUMMA_CPUS_PER_TASK: 32
SETTINGS_SUMMA_TIME_LIMIT: 01:00:00
SETTINGS_SUMMA_MEM: 5
SETTINGS_SUMMA_GRU_COUNT: 85
SETTINGS_SUMMA_GRU_PER_JOB: 5
SETTINGS_SUMMA_PARALLEL_PATH: default
SETTINGS_SUMMA_PARALLEL_EXE: summa_actors.exe
EXPERIMENT_OUTPUT_SUMMA: default
EXPERIMENT_LOG_SUMMA: default
PARAMS_TO_CALIBRATE: tempCritRain,k_soil,vGn_n,theta_sat
BASIN_PARAMS_TO_CALIBRATE: routingGammaScale
SUMMA_DECISION_OPTIONS:
  snowIncept:
  - lightSnow
  compaction:
  - anderson
  snowLayers:
  - CLM_2010
  alb_method:
  - conDecay
  thCondSnow:
  - smnv2000
  - jrdn1991
  vegeParTbl:
  - MODIFIED_IGBP_MODIS_NOAH
  soilStress:
  - NoahType
  stomResist:
  - BallBerry
  LAI_method:
  - monTable
  veg_traits:
  - Raupach_BLM1994
  canopyEmis:
  - difTrans
  windPrfile:
  - logBelowCanopy
  canopySrad:
  - BeersLaw
  soilCatTbl:
  - ROSETTA
  f_Richards:
  - mixdform
  groundwatr:
  - bigBuckt
  hc_profile:
  - constant
  bcLowrSoiH:
  - drainage
  thCondSoil:
  - funcSoilWet
  spatial_gw:
  - localColumn
  subRouting:
  - timeDlay
  num_method:
  - itertive
  fDerivMeth:
  - analytic
  bcUpprTdyn:
  - nrg_flux
  bcLowrTdyn:
  - zeroFlux
  bcUpprSoiH:
  - liq_flux
  astability:
  - louisinv
CALIBRATE_DEPTH: false
DEPTH_TOTAL_MULT_BOUNDS:
- 0.1
- 5.0
DEPTH_SHAPE_FACTOR_BOUNDS:
- 0.1
- 3.0
SETTINGS_SUMMA_GLACIER_MODE: false
SETTINGS_SUMMA_GLACIER_ATTRIBUTES: attributes_glac.nc
SETTINGS_SUMMA_GLACIER_COLDSTATE: coldState_glac.nc
SUMMA_TIMEOUT: 7200
FUSE_INSTALL_PATH: default
FUSE_EXE: fuse.exe
FUSE_ROUTING_INTEGRATION: default
SETTINGS_FUSE_PATH: default
SETTINGS_FUSE_FILEMANAGER: default
FUSE_SPATIAL_MODE: distributed
FUSE_SUBCATCHMENT_DIM: longitude
EXPERIMENT_OUTPUT_FUSE: default
SETTINGS_FUSE_PARAMS_TO_CALIBRATE: MAXWATR_1,MAXWATR_2,BASERTE,QB_POWR,TIMEDELAY,PERCRTE,FRACTEN,RTFRAC1,MBASE,MFMAX,MFMIN,PXTEMP,LAPSE
FUSE_DECISION_OPTIONS:
  RFERR:
  - additive_e
  - multiplc_e
  ARCH1:
  - tension1_1
  ARCH2:
  - tens2pll_2
  QSURF:
  - arno_x_vic
  - prms_varnt
  QPERC:
  - perc_f2sat
  ESOIL:
  - sequential
  QINTF:
  - intflwnone
  Q_TDH:
  - rout_gamma
  SNOWM:
  - temp_index
FUSE_N_ELEVATION_BANDS: 1
FUSE_TIMEOUT: 3600
GR_INSTALL_PATH: default
GR_EXE: GR.r
GR_SPATIAL_MODE: lumped
GR_ROUTING_INTEGRATION: none
SETTINGS_GR_PATH: default
SETTINGS_GR_CONTROL: default
GR_PARAMS_TO_CALIBRATE: X1,X2,X3,X4,CTG,Kf,Gratio,Albedo_diff
HYPE_INSTALL_PATH: default
HYPE_EXE: hype
SETTINGS_HYPE_PATH: default
SETTINGS_HYPE_INFO: info.txt
HYPE_PARAMS_TO_CALIBRATE: ttmp,cmlt,cevp,lp,epotdist,rrcs1,rrcs2,rcgrw,rivvel,damp
HYPE_SPINUP_DAYS: 365
NGEN_INSTALL_PATH: default
NGEN_EXE: ngen
NGEN_MODULES_TO_CALIBRATE: CFE
NGEN_CFE_PARAMS_TO_CALIBRATE: smcmax,satdk,bb,slop,Cgw,expon,max_gw_storage,K_nash,K_lf
NGEN_NOAH_PARAMS_TO_CALIBRATE: rain_snow_thresh,ZREF,noah_refdk,noah_refkdt,noah_czil,noah_z0,noah_frzk,noah_salp
NGEN_PET_PARAMS_TO_CALIBRATE: pet_albedo,pet_z0_mom,pet_z0_heat,pet_veg_h,pet_d0
NGEN_ACTIVE_CATCHMENT_ID: cat-1
MESH_INSTALL_PATH: default
MESH_EXE: mesh.exe
MESH_SPATIAL_MODE: auto
SETTINGS_MESH_PATH: default
EXPERIMENT_OUTPUT_MESH: default
MESH_FORCING_PATH: default
MESH_FORCING_VARS: default
MESH_FORCING_UNITS: default
MESH_FORCING_TO_UNITS: default
MESH_LANDCOVER_STATS_PATH: default
MESH_LANDCOVER_STATS_DIR: default
MESH_LANDCOVER_STATS_FILE: default
MESH_MAIN_ID: default
MESH_DS_MAIN_ID: default
MESH_LANDCOVER_CLASSES: default
MESH_DDB_VARS: default
MESH_DDB_UNITS: default
MESH_DDB_TO_UNITS: default
MESH_DDB_MIN_VALUES: default
MESH_GRU_DIM: default
MESH_HRU_DIM: default
MESH_OUTLET_VALUE: default
SETTINGS_MESH_INPUT: default
MESH_PARAMS_TO_CALIBRATE: ZSNL,MANN,RCHARG,BASEFLW,DTMINUSR
MESH_SPINUP_DAYS: 365
MESH_GRU_MIN_TOTAL: 0.0
INSTALL_PATH_MIZUROUTE: default
EXE_NAME_MIZUROUTE: mizuRoute.exe
SETTINGS_MIZU_PATH: default
SETTINGS_MIZU_WITHIN_BASIN: 0
SETTINGS_MIZU_ROUTING_DT: 86400
SETTINGS_MIZU_ROUTING_UNITS: m/s
SETTINGS_MIZU_ROUTING_VAR: q_routed
SETTINGS_MIZU_OUTPUT_FREQ: single
SETTINGS_MIZU_OUTPUT_VARS: '1'
SETTINGS_MIZU_MAKE_OUTLET: n/a
SETTINGS_MIZU_NEEDS_REMAP: false
SETTINGS_MIZU_TOPOLOGY: topology.nc
SETTINGS_MIZU_PARAMETERS: param.nml.default
SETTINGS_MIZU_CONTROL_FILE: mizuroute.control
SETTINGS_MIZU_REMAP: routing_remap.nc
MIZU_FROM_MODEL: default
EXPERIMENT_LOG_MIZUROUTE: default
EXPERIMENT_OUTPUT_MIZUROUTE: default
SETTINGS_MIZU_OUTPUT_VAR: IRFroutedRunoff
SETTINGS_MIZU_PARAMETER_FILE: param.nml.default
SETTINGS_MIZU_REMAP_FILE: routing_remap.nc
SETTINGS_MIZU_TOPOLOGY_FILE: topology.nc
MIZUROUTE_PARAMS_TO_CALIBRATE: velo,diff
CALIBRATE_MIZUROUTE: false
MIZUROUTE_TIMEOUT: 3600
LSTM_LOAD: false
LSTM_HIDDEN_SIZE: 128
LSTM_NUM_LAYERS: 3
LSTM_EPOCHS: 300
LSTM_BATCH_SIZE: 64
LSTM_LEARNING_RATE: 0.001
LSTM_LEARNING_PATIENCE: 30
LSTM_LOOKBACK: 700
LSTM_DROPOUT: 0.2
LSTM_L2_REGULARIZATION: 1.0e-06
LSTM_USE_ATTENTION: true
LSTM_USE_SNOW: false
LSTM_TRAIN_THROUGH_ROUTING: false
OPTIMIZATION_METHODS:
- iteration
OPTIMIZATION_TARGET: streamflow
CALIBRATION_VARIABLE: streamflow
CALIBRATION_TIMESTEP: daily
ITERATIVE_OPTIMIZATION_ALGORITHM: DE
OPTIMIZATION_METRIC: KGE
NUMBER_OF_ITERATIONS: 10
POPULATION_SIZE: 5
FINAL_EVALUATION_NUMERICAL_METHOD: ida
CLEANUP_PARALLEL_DIRS: true
SWRMSIZE: 20
PSO_COGNITIVE_PARAM: 1.5
PSO_SOCIAL_PARAM: 1.5
PSO_INERTIA_WEIGHT: 0.7
PSO_INERTIA_REDUCTION_RATE: 0.99
INERTIA_SCHEDULE: LINEAR
DE_SCALING_FACTOR: 0.5
DE_CROSSOVER_RATE: 0.9
DDS_R: 0.2
ASYNC_DDS_POOL_SIZE: 10
ASYNC_DDS_BATCH_SIZE: 10
MAX_STAGNATION_BATCHES: 10
NUMBER_OF_COMPLEXES: 2
POINTS_PER_SUBCOMPLEX: 5
NUMBER_OF_EVOLUTION_STEPS: 20
EVOLUTION_STAGNATION: 5
PERCENT_CHANGE_THRESHOLD: 0.01
NSGA2_MULTI_TARGET: false
NSGA2_PRIMARY_TARGET: streamflow
OPTIMIZATION_TARGET2: gw_depth
NSGA2_PRIMARY_METRIC: KGE
OPTIMIZATION_METRIC2: KGE
NSGA2_CROSSOVER_RATE: 0.9
NSGA2_MUTATION_RATE: 0.1
NSGA2_ETA_C: 20
NSGA2_ETA_M: 20
DPE_TRAINING_CACHE: default
DPE_HIDDEN_DIMS:
- 256
- 128
- 64
DPE_TRAINING_SAMPLES: 500
DPE_VALIDATION_SAMPLES: 100
DPE_EPOCHS: 300
DPE_LEARNING_RATE: 0.001
DPE_OPTIMIZATION_LR: 0.01
DPE_OPTIMIZATION_STEPS: 200
DPE_OPTIMIZER: ADAM
DPE_OBJECTIVE_WEIGHTS:
  KGE: 1.0
DPE_EMULATOR_ITERATE: true
DPE_ITERATE_MAX_ITERATIONS: 5
DPE_ITERATE_SAMPLES_PER_CYCLE: 100
DPE_ITERATE_SAMPLING_RADIUS: 0.1
DPE_ITERATE_CONVERGENCE_TOL: 0.0001
DPE_ITERATE_MIN_IMPROVEMENT: 1.0e-06
DPE_ITERATE_SAMPLING_METHOD: gaussian
DPE_USE_NN_HEAD: true
DPE_PRETRAIN_NN_HEAD: false
DPE_USE_SUNDIALS: true
DPE_AUTODIFF_STEPS: 100
DPE_AUTODIFF_LR: 0.001
DPE_FD_STEP: 0.005
DPE_GD_STEP_SIZE: 0.1
LARGE_DOMAIN_EMULATION_ENABLED: true
EMULATOR_SETTING: SUMMA_AUTODIFF_FD
LARGE_DOMAIN_EMULATOR_MODE: SUMMA_AUTODIFF
LARGE_DOMAIN_EMULATOR_OPTIMIZER: Adam
LARGE_DOMAIN_TRAINING_EPOCHS: 100
LARGE_DOMAIN_PARAMETER_ENSEMBLE_SIZE: 1000
LARGE_DOMAIN_BATCH_SIZE: 32
LARGE_DOMAIN_EMULATOR_PRETRAIN_NN_HEAD: true
LARGE_DOMAIN_EMULATOR_USE_NN_HEAD: true
LARGE_DOMAIN_EMULATOR_TRAINING_SAMPLES: 500
LARGE_DOMAIN_EMULATOR_EPOCHS: 50
LARGE_DOMAIN_EMULATOR_AUTODIFF_STEPS: 100
LARGE_DOMAIN_EMULATOR_STREAMFLOW_WEIGHT: 0.5
LARGE_DOMAIN_EMULATOR_SMAP_WEIGHT: 0.2
LARGE_DOMAIN_EMULATOR_GRACE_WEIGHT: 0.15
LARGE_DOMAIN_EMULATOR_MODIS_WEIGHT: 0.15
EMULATION_NUM_SAMPLES: 100
EMULATION_SEED: 22
EMULATION_SAMPLING_METHOD: lhs
EMULATION_PARALLEL_ENSEMBLE: false
EMULATION_MAX_PARALLEL_JOBS: 100
EMULATION_SKIP_MIZUROUTE: false
EMULATION_USE_ATTRIBUTES: false
EMULATION_MAX_ITERATIONS: 3
EVALUATION_DATA:
- streamflow
ANALYSES:
- benchmarking
- attributes
SIM_REACH_ID: 123
DOWNLOAD_WSC_DATA: true
STATION_ID: 05BB001
STREAMFLOW_RAW_PATH: default
STREAMFLOW_RAW_NAME: default
STREAMFLOW_PROCESSED_PATH: default
HYDAT_PATH: default
DOWNLOAD_SNOTEL: false
SNOTEL_PATH: /path/to/data/geospatial-data/SNOTEL
DOWNLOAD_FLUXNET: false
FLUXNET_PATH: /path/to/data/data/geospatial-data/fluxnet
DOWNLOAD_USGS_GW: false
USGS_STATION: '1674432'
DOWNLOAD_SMAP: false
SMAP_PRODUCT: SPL4SMGP
SMAP_PATH: default
SMAP_USE_OPENDAP: false
SMAP_SURFACE_DEPTH_M: 0.05
SMAP_ROOTZONE_DEPTH_M: 1.0
ISMN_PATH: default
ISMN_API_BASE: https://ismn.earth/dataviewer
ISMN_METADATA_URL: https://ismn.earth/static/dataviewer/network_station_details.json
ISMN_MAX_STATIONS: 3
ISMN_TARGET_DEPTH_M: 0.05
ISMN_TEMPORAL_AGGREGATION: daily_mean
DOWNLOAD_GRACE: false
GRACE_PRODUCT: RL06
GRACE_PATH: default
GRACE_DATA_DIR: default
DOWNLOAD_MODIS_SNOW: false
MODIS_SNOW_PRODUCT: MOD10A1.006
MODIS_SNOW_PATH: default
MODIS_SNOW_DIR: default
MODIS_MIN_PIXELS: 100
MODIS_SCA_MERGE: true
MODIS_SCA_PRODUCTS:
- MOD10A1.061
- MYD10A1.061
MODIS_SCA_MERGE_STRATEGY: max
MODIS_SCA_CLOUD_FILTER: true
MODIS_SCA_MIN_VALID_RATIO: 0.1
MODIS_SCA_NORMALIZE: true
MODIS_SCA_USE_CATCHMENT_MASK: false
DOWNLOAD_MODIS_ET: false
MODIS_ET_PRODUCT: MOD16A2.061
MODIS_ET_PATH: default
MOD16_ET_DIR: default
ATTRIBUTES_DATA_DIR: default
ATTRIBUTES_SOILGRIDS_PATH: default
ATTRIBUTES_PELLETIER_PATH: default
ATTRIBUTES_MERIT_PATH: default
ATTRIBUTES_MODIS_PATH: default
ATTRIBUTES_GLCLU_PATH: default
ATTRIBUTES_FOREST_HEIGHT_PATH: default
ATTRIBUTES_WORLDCLIM_PATH: default
ATTRIBUTES_GLIM_PATH: default
ATTRIBUTES_GROUNDWATER_PATH: default
ATTRIBUTES_STREAMFLOW_PATH: default
ATTRIBUTES_GLWD_PATH: default
ATTRIBUTES_HYDROLAKES_PATH: default
ATTRIBUTES_OUTPUT_DIR: default
HRU_GAUGE_MAPPING: {}
CATCHMENT_PATH: default
CATCHMENT_SHP_NAME: default
CATCHMENT_SHP_LAT: center_lat
CATCHMENT_SHP_LON: center_lon
CATCHMENT_SHP_AREA: HRU_area
CATCHMENT_SHP_HRUID: HRU_ID
CATCHMENT_SHP_GRUID: GRU_ID
RIVER_BASINS_PATH: default
RIVER_BASINS_NAME: default
RIVER_BASIN_SHP_RM_GRUID: GRU_ID
RIVER_BASIN_SHP_HRU_TO_SEG: gru_to_seg
RIVER_BASIN_SHP_AREA: GRU_area
RIVER_NETWORK_SHP_PATH: default
RIVER_NETWORK_SHP_NAME: default
RIVER_NETWORK_SHP_LENGTH: Length
RIVER_NETWORK_SHP_SEGID: LINKNO
RIVER_NETWORK_SHP_DOWNSEGID: DSLINKNO
RIVER_NETWORK_SHP_SLOPE: Slope
POUR_POINT_SHP_PATH: default
POUR_POINT_SHP_NAME: default
FORCING_PATH: default
OBSERVATIONS_PATH: default
SIMULATIONS_PATH: default
INTERSECT_SOIL_PATH: default
INTERSECT_SOIL_NAME: default
INTERSECT_ROUTING_PATH: default
INTERSECT_ROUTING_NAME: default
INTERSECT_DEM_PATH: default
INTERSECT_DEM_NAME: default
INTERSECT_LAND_PATH: default
INTERSECT_LAND_NAME: default
OUTPUT_BASINS_PATH: default
OUTPUT_RIVERS_PATH: default
DEM_PATH: default
DEM_NAME: default
SOURCE_GEOFABRIC_BASINS_PATH: default
SOURCE_GEOFABRIC_RIVERS_PATH: default
TAUDEM_DIR: default
OUTPUT_DIR: default
CATCHMENT_PLOT_DIR: default
SOIL_CLASS_PATH: default
SOIL_CLASS_NAME: default
LAND_CLASS_PATH: default
RADIATION_PATH: default
DATATOOL_PATH: default
GISTOOL_PATH: default
EASYMORE_CLIENT: easymore cli
DATATOOL_DATASET_ROOT: /path/to/meteorological-data/
GISTOOL_DATASET_ROOT: /path/to/geospatial-data/
TOOL_CACHE: /path/to/cache/dir
EASYMORE_CACHE: /path/to/cache/dir
EASYMORE_JOB_CONF: /path/to/esmr/job_config
CLUSTER_JSON: /path/to/cluster.json
GISTOOL_LIB_PATH: /path/to/r-env/
SETTINGS_BASE_DIR: src/symfluence/resources/base_settings
EM_EARTH_REGION: NorthAmerica
LARGE_DOMAIN_EMULATOR_HIDDEN_DIM: 512
LARGE_DOMAIN_EMULATOR_N_HEADS: 8
LARGE_DOMAIN_EMULATOR_N_LAYERS: 6
LARGE_DOMAIN_EMULATOR_DROPOUT: 0.1
LARGE_DOMAIN_EMULATOR_BATCH_SIZE: 16
LARGE_DOMAIN_EMULATOR_LEARNING_RATE: 0.0001
LARGE_DOMAIN_EMULATOR_VALIDATION_SPLIT: 0.2
LARGE_DOMAIN_EMULATOR_WINDOW_DAYS: 30
LARGE_DOMAIN_EMULATOR_OPTIMIZATION_STEPS: 200
LARGE_DOMAIN_EMULATOR_OPTIMIZATION_LR: 0.01
LARGE_DOMAIN_EMULATOR_FD_STEP: 0.001
LARGE_DOMAIN_EMULATOR_FD_STEPS: 100
LARGE_DOMAIN_EMULATOR_FD_STEP_SIZE: 0.1
LARGE_DOMAIN_EMULATOR_AUTODIFF_LR: 0.01
