SYMFLUENCE_DATA_DIR: /anvil/projects/x-ees250064/users/darri/SYMFLUENCE_data
SYMFLUENCE_CODE_DIR: /anvil/projects/x-ees250064/users/darri/SYMFLUENCE
NUM_PROCESSES: 1
DEBUG_MODE: false
LOG_LEVEL: INFO
LOG_TO_FILE: true
STOP_ON_ERROR: true
DOMAIN_NAME: Bow_at_Banff_lumped
EXPERIMENT_ID: run_1
EXPERIMENT_TIME_START: 2004-01-01 01:00
EXPERIMENT_TIME_END: 2007-12-31 23:00
CALIBRATION_PERIOD: 2005-10-01, 2006-09-30
EVALUATION_PERIOD: 2006-10-01, 2007-09-30
SPINUP_PERIOD: 2004-01-01, 2005-09-30
DOMAIN_DEFINITION_METHOD: lumped
SUB_GRID_DISCRETIZATION: GRUs
POUR_POINT_COORDS: 51.1722/-115.5717
ROUTING_DELINEATION: lumped
DELINEATION_METHOD: stream_threshold
STREAM_THRESHOLD: 5000.0
MIN_SOURCE_THRESHOLD: 100
LUMPED_WATERSHED_METHOD: TauDEM
DELINEATE_BY_POURPOINT: true
DATA_ACCESS: cloud
DOWNLOAD_DEM: true
DOWNLOAD_SOIL: true
DOWNLOAD_LAND_COVER: true
DEM_SOURCE: copernicus
LAND_CLASS_SOURCE: modis
FORCING_DATASET: ERA5
FORCING_TIME_STEP_SIZE: 3600
FORCING_MEASUREMENT_HEIGHT: 2.0
APPLY_LAPSE_RATE: true
LAPSE_RATE: 0.0065
PET_METHOD: oudin
ERA5_ZARR_PATH: gcp-public-data-arco-era5/ar/full_37-1h-0p25deg-chunk-1.zarr-v3
ERA5_TIME_STEP_HOURS: 1
HYDROLOGICAL_MODEL: SUMMA
ROUTING_MODEL: none
SUMMA_INSTALL_PATH: default
SUMMA_EXE: summa_sundials.exe
MIZUROUTE_INSTALL_PATH: default
MIZUROUTE_EXE: mizuRoute.exe
SUMMA_TIMEOUT: 7200
MIZUROUTE_TIMEOUT: 3600
OPTIMIZATION_METHODS:
- iteration
OPTIMIZATION_TARGET: streamflow
CALIBRATION_VARIABLE: streamflow
CALIBRATION_TIMESTEP: hourly
ITERATIVE_OPTIMIZATION_ALGORITHM: DDS
OPTIMIZATION_METRIC: KGE
NUMBER_OF_ITERATIONS: 100
DDS_R: 0.2
PARAMS_TO_CALIBRATE: k_soil,theta_sat,aquiferBaseflowExp,aquiferBaseflowRate,qSurfScale,summerLAI,frozenPrecipMultip,Fcapil,tempCritRain,heightCanopyTop,heightCanopyBottom,windReductionParam,vGn_n
BASIN_PARAMS_TO_CALIBRATE: routingGammaScale,routingGammaShape
FINAL_EVALUATION_NUMERICAL_METHOD: ida
DOWNLOAD_WSC_DATA: true
STATION_ID: 05BB001
