ANALYSES:
- benchmarking
- attributes
APPLY_LAPSE_RATE: true
AREA_EXPONENT: 1.0
ASPECT_CLASS_NUMBER: 8
ASPECT_PATH: default
ASYNC_DDS_BATCH_SIZE: 10
ASYNC_DDS_POOL_SIZE: 10
ATTRIBUTES_DATA_DIR: default
ATTRIBUTES_FOREST_HEIGHT_PATH: default
ATTRIBUTES_GLCLU_PATH: default
ATTRIBUTES_GLIM_PATH: default
ATTRIBUTES_GLWD_PATH: default
ATTRIBUTES_GROUNDWATER_PATH: default
ATTRIBUTES_HYDROLAKES_PATH: default
ATTRIBUTES_MERIT_PATH: default
ATTRIBUTES_MODIS_PATH: default
ATTRIBUTES_OUTPUT_DIR: default
ATTRIBUTES_PELLETIER_PATH: default
ATTRIBUTES_SOILGRIDS_PATH: default
ATTRIBUTES_STREAMFLOW_PATH: default
ATTRIBUTES_WORLDCLIM_PATH: default
BASIN_PARAMS_TO_CALIBRATE: routingGammaScale
BOUNDING_BOX_COORDS: 59.88/17.59/59.86/17.61
CALIBRATE_DEPTH: false
CALIBRATION_PERIOD: 2020-01-02, 2020-01-03
CALIBRATION_TIMESTEP: daily
CATCHMENT_PATH: default
CATCHMENT_PLOT_DIR: default
CATCHMENT_SHP_AREA: HRU_area
CATCHMENT_SHP_GRUID: GRU_ID
CATCHMENT_SHP_HRUID: HRU_ID
CATCHMENT_SHP_LAT: center_lat
CATCHMENT_SHP_LON: center_lon
CATCHMENT_SHP_NAME: default
CLEANUP_INTERMEDIATE_FILES: false
CLUSTER_JSON: /path/to/cluster.json
CURVATURE_THRESHOLD: 0.0
DATATOOL_DATASET_ROOT: /path/to/meteorological-data/
DATATOOL_PATH: default
DATA_ACCESS: cloud
DDS_R: 0.2
DELINEATE_BY_POURPOINT: true
DELINEATE_COASTAL_WATERSHEDS: false
DELINEATION_METHOD: stream_threshold
DEM_NAME: default
DEM_PATH: default
DEM_SOURCE: copernicus
DEPTH_SHAPE_FACTOR_BOUNDS:
- 0.1
- 3.0
DEPTH_TOTAL_MULT_BOUNDS:
- 0.1
- 5.0
DE_CROSSOVER_RATE: 0.9
DE_SCALING_FACTOR: 0.5
DOMAIN_DEFINITION_METHOD: lumped
SUB_GRID_DISCRETIZATION: GRUs
DOMAIN_NAME: fyris_uppsala
DOWNLOAD_FLUXNET: false
DOWNLOAD_GRACE: false
DOWNLOAD_MODIS_SNOW: false
DOWNLOAD_SMAP: false
DOWNLOAD_SNOTEL: false
DOWNLOAD_USGS_DATA: false
DOWNLOAD_USGS_GW: false
DOWNLOAD_WSC_DATA: true
DPE_AUTODIFF_LR: 0.001
DPE_AUTODIFF_STEPS: 100
DPE_EMULATOR_ITERATE: true
DPE_EPOCHS: 300
DPE_FD_STEP: 0.005
DPE_GD_STEP_SIZE: 0.1
DPE_HIDDEN_DIMS:
- 256
- 128
- 64
DPE_ITERATE_CONVERGENCE_TOL: 1e-4
DPE_ITERATE_MAX_ITERATIONS: 5
DPE_ITERATE_MIN_IMPROVEMENT: 1e-6
DPE_ITERATE_SAMPLES_PER_CYCLE: 100
DPE_ITERATE_SAMPLING_METHOD: gaussian
DPE_ITERATE_SAMPLING_RADIUS: 0.1
DPE_LEARNING_RATE: 1e-3
DPE_OBJECTIVE_WEIGHTS:
  KGE: 1.0
DPE_OPTIMIZATION_LR: 1e-2
DPE_OPTIMIZATION_STEPS: 200
DPE_OPTIMIZER: ADAM
DPE_PRETRAIN_NN_HEAD: false
DPE_TRAINING_CACHE: default
DPE_TRAINING_SAMPLES: 500
DPE_USE_NN_HEAD: true
DPE_USE_SUNDIALS: true
DPE_VALIDATION_SAMPLES: 100
DROP_ANALYSIS_LOG_SPACING: true
DROP_ANALYSIS_MAX_THRESHOLD: 10000
DROP_ANALYSIS_MIN_THRESHOLD: 100
DROP_ANALYSIS_NUM_THRESHOLDS: 10
EASYMORE_CACHE: /path/to/cache/dir
EASYMORE_CLIENT: easymore cli
EASYMORE_JOB_CONF: /path/to/esmr/job_config
ELEVATION_BAND_SIZE: 200
EMULATION_MAX_ITERATIONS: 3
EMULATION_MAX_PARALLEL_JOBS: 100
EMULATION_NUM_SAMPLES: 100
EMULATION_PARALLEL_ENSEMBLE: false
EMULATION_SAMPLING_METHOD: lhs
EMULATION_SEED: 22
EMULATION_SKIP_MIZUROUTE: false
EMULATION_USE_ATTRIBUTES: false
EM_EARTH_DATA_TYPE: deterministic
EM_EARTH_MAX_EXPANSION: 0.2
EM_EARTH_MIN_BBOX_SIZE: 0.1
EM_EARTH_PRCP_DIR: /path/to/EM-EARTH/prcp/data
EM_EARTH_TMEAN_DIR: /path/to/EM-EARTH/tmean/data
EM_PRCP: prcp
EVALUATION_DATA:
- streamflow
EVALUATION_PERIOD: 2020-01-02, 2020-01-03
EVOLUTION_STAGNATION: 5
EXE_NAME_MIZUROUTE: mizuRoute.exe
EXPERIMENT_ID: calib_demo_short
EXPERIMENT_LOG_MIZUROUTE: default
EXPERIMENT_LOG_SUMMA: default
EXPERIMENT_OUTPUT_FUSE: default
EXPERIMENT_OUTPUT_MESH: default
EXPERIMENT_OUTPUT_MIZUROUTE: default
EXPERIMENT_OUTPUT_SUMMA: default
EXPERIMENT_TIME_END: 2020-01-03 00:00
EXPERIMENT_TIME_START: 2020-01-01 00:00
FLASH_BATCH_SIZE: 64
FLASH_DROPOUT: 0.2
FLASH_EPOCHS: 300
FLASH_HIDDEN_SIZE: 128
FLASH_L2_REGULARIZATION: 1e-6
FLASH_LEARNING_PATIENCE: 30
FLASH_LEARNING_RATE: 0.001
FLASH_LOAD: false
FLASH_LOOKBACK: 700
FLASH_NUM_LAYERS: 3
FLASH_USE_ATTENTION: true
FLASH_USE_SNOW: false
FLUXNET_PATH: /path/to/data/data/geospatial-data/fluxnet
FLUXNET_STATION: null
FORCE_RUN_ALL_STEPS: false
FORCING_DATASET: CERRA
FORCING_MEASUREMENT_HEIGHT: 2
FORCING_PATH: default
FORCING_SHAPE_LAT_NAME: lat
FORCING_SHAPE_LON_NAME: lon
FORCING_TIME_STEP_SIZE: 3600
FORCING_VARIABLES: default
FUSE_DECISION_OPTIONS:
  ARCH1:
  - tension1_1
  ARCH2:
  - tens2pll_2
  ESOIL:
  - sequential
  QINTF:
  - intflwnone
  QPERC:
  - perc_f2sat
  QSURF:
  - arno_x_vic
  - prms_varnt
  Q_TDH:
  - rout_gamma
  RFERR:
  - additive_e
  - multiplc_e
  SNOWM:
  - temp_index
FUSE_EXE: fuse.exe
FUSE_INSTALL_PATH: default
FUSE_ROUTING_INTEGRATION: default
FUSE_SPATIAL_MODE: distributed
GEOFABRIC_TYPE: na
GISTOOL_DATASET_ROOT: /path/to/geospatial-data/
GISTOOL_LIB_PATH: /path/to/r-env/
GISTOOL_PATH: default
GRACE_PATH: default
GRACE_PRODUCT: RL06
GR_EXE: GR.r
GR_INSTALL_PATH: default
GR_SPATIAL_MODE: lumped
HRU_GAUGE_MAPPING: {}
HYDAT_PATH: default
HYDROLOGICAL_MODEL: SUMMA
HYPE_INSTALL_PATH: default
INERTIA_SCHEDULE: LINEAR
INSTALL_PATH_MIZUROUTE: default
INTERSECT_DEM_NAME: default
INTERSECT_DEM_PATH: default
INTERSECT_LAND_NAME: default
INTERSECT_LAND_PATH: default
INTERSECT_ROUTING_NAME: default
INTERSECT_ROUTING_PATH: default
INTERSECT_SOIL_NAME: default
INTERSECT_SOIL_PATH: default
ITERATIVE_OPTIMIZATION_ALGORITHM: DDS
LAND_CLASS_NAME: default
LAND_CLASS_PATH: default
LAPSE_RATE: 0.0065
LOG_FORMAT: detailed
LOG_LEVEL: INFO
LOG_TO_FILE: true
LUMPED_WATERSHED_METHOD: TauDEM
MAX_STAGNATION_BATCHES: 10
MESH_DDB_MIN_VALUES: default
MESH_DDB_TO_UNITS: default
MESH_DDB_UNITS: default
MESH_DDB_VARS: default
MESH_DS_MAIN_ID: default
MESH_EXE: mesh.exe
MESH_FORCING_PATH: default
MESH_FORCING_TO_UNITS: default
MESH_FORCING_UNITS: default
MESH_FORCING_VARS: default
MESH_GRU_DIM: default
MESH_HRU_DIM: default
MESH_INSTALL_PATH: default
MESH_LANDCOVER_CLASSES: default
MESH_LANDCOVER_STATS_DIR: default
MESH_LANDCOVER_STATS_FILE: default
MESH_LANDCOVER_STATS_PATH: default
MESH_MAIN_ID: default
MESH_OUTLET_VALUE: default
MIN_GRU_SIZE: 0
MIN_HRU_SIZE: 4
MIN_SOURCE_THRESHOLD: 100
MIZU_FROM_MODEL: default
MODIS_SNOW_PATH: default
MODIS_SNOW_PRODUCT: MOD10A1.006
MOVE_OUTLETS_MAX_DISTANCE: 200
NUM_PROCESSES: 1
MULTI_SCALE_THRESHOLDS: 10000,5000,2500,1000,500
NEX_ENSEMBLES:
- r1i1p1f1
NEX_MODELS:
- ACCESS-CM2
- GFDL-ESM4
NEX_SCENARIOS:
- historical
NEX_VARIABLES:
- hurs
- huss
- pr
- rlds
- rsds
- sfcWind
- tas
- tasmax
- tasmin
NGEN_ACTIVE_CATCHMENT_ID: cat-1
NGEN_CFE_PARAMS_TO_CALIBRATE: smcmax,satdk,bb,slop,Cgw,expon,max_gw_storage,K_nash,K_lf
NGEN_EXE: ngen
NGEN_INSTALL_PATH: default
NGEN_MODULES_TO_CALIBRATE: CFE
NGEN_NOAH_PARAMS_TO_CALIBRATE: rain_snow_thresh,ZREF,noah_refdk,noah_refkdt,noah_czil,noah_z0,noah_frzk,noah_salp
NGEN_PET_PARAMS_TO_CALIBRATE: pet_albedo,pet_z0_mom,pet_z0_heat,pet_veg_h,pet_d0
NSGA2_CROSSOVER_RATE: 0.9
NSGA2_ETA_C: 20
NSGA2_ETA_M: 20
NSGA2_MULTI_TARGET: false
NSGA2_MUTATION_RATE: 0.1
NSGA2_PRIMARY_METRIC: KGE
NSGA2_PRIMARY_TARGET: streamflow
NSGA2_SECONDARY_METRIC: KGE
NSGA2_SECONDARY_TARGET: gw_depth
NUMBER_OF_COMPLEXES: 2
NUMBER_OF_EVOLUTION_STEPS: 20
NUMBER_OF_ITERATIONS: 5
OBSERVATIONS_PATH: default
OPTIMIZATION_METHODS:
- iteration
OPTIMIZATION_METRIC: KGE
OPTIMIZATION_TARGET: streamflow
OUTPUT_BASINS_PATH: default
OUTPUT_DIR: default
OUTPUT_RIVERS_PATH: default
PARAMS_TO_CALIBRATE: k_soil,theta_sat
PERCENT_CHANGE_THRESHOLD: 0.01
PET_METHOD: oudin
POINTS_PER_SUBCOMPLEX: 5
POPULATION_SIZE: 5
POUR_POINT_COORDS: 59.87/17.60
POUR_POINT_SHP_NAME: default
POUR_POINT_SHP_PATH: default
PSO_COGNITIVE_PARAM: 1.5
PSO_INERTIA_REDUCTION_RATE: 0.99
PSO_INERTIA_WEIGHT: 0.7
PSO_SOCIAL_PARAM: 1.5
RADIATION_CLASS_NUMBER: 5
RADIATION_PATH: default
RANDOM_SEED: null
RIVER_BASINS_NAME: default
RIVER_BASINS_PATH: default
RIVER_BASIN_SHP_AREA: GRU_area
RIVER_BASIN_SHP_HRU_TO_SEG: gru_to_seg
RIVER_BASIN_SHP_RM_GRUID: GRU_ID
RIVER_NETWORK_SHP_DOWNSEGID: DSLINKNO
RIVER_NETWORK_SHP_LENGTH: Length
RIVER_NETWORK_SHP_NAME: default
RIVER_NETWORK_SHP_PATH: default
RIVER_NETWORK_SHP_SEGID: LINKNO
RIVER_NETWORK_SHP_SLOPE: Slope
ROUTING_DELINEATION: lumped
ROUTING_MODEL: mizuRoute
SETTINGS_FUSE_FILEMANAGER: default
SETTINGS_FUSE_PARAMS_TO_CALIBRATE: MAXWATR_1,MAXWATR_2,BASERTE,QB_POWR,TIMEDELAY,PERCRTE,FRACTEN,RTFRAC1,MBASE,MFMAX,MFMIN,PXTEMP,LAPSE
SETTINGS_FUSE_PATH: default
SETTINGS_GR_CONTROL: default
SETTINGS_GR_PATH: default
SETTINGS_HYPE_PATH: default
SETTINGS_MESH_PATH: default
SETTINGS_MIZU_CONTROL_FILE: mizuroute.control
SETTINGS_MIZU_MAKE_OUTLET: n/a
SETTINGS_MIZU_NEEDS_REMAP: false
SETTINGS_MIZU_OUTPUT_FREQ: single
SETTINGS_MIZU_OUTPUT_VARS: 1
SETTINGS_MIZU_PARAMETERS: param.nml.default
SETTINGS_MIZU_PATH: default
SETTINGS_MIZU_REMAP: routing_remap.nc
SETTINGS_MIZU_ROUTING_DT: 86400
SETTINGS_MIZU_ROUTING_UNITS: mm/d
SETTINGS_MIZU_ROUTING_VAR: q_routed
SETTINGS_MIZU_TOPOLOGY: topology.nc
SETTINGS_MIZU_WITHIN_BASIN: 0
SETTINGS_SUMMA_ATTRIBUTES: attributes.nc
SETTINGS_SUMMA_BASIN_PARAMS_FILE: basinParamInfo.txt
SETTINGS_SUMMA_COLDSTATE: coldState.nc
SETTINGS_SUMMA_CONNECT_HRUS: true
SETTINGS_SUMMA_CPUS_PER_TASK: 32
SETTINGS_SUMMA_FILEMANAGER: fileManager.txt
SETTINGS_SUMMA_FORCING_LIST: forcingFileList.txt
SETTINGS_SUMMA_GRU_COUNT: 85
SETTINGS_SUMMA_GRU_PER_JOB: 5
SETTINGS_SUMMA_LOCAL_PARAMS_FILE: localParamInfo.txt
SETTINGS_SUMMA_MEM: 5
SETTINGS_SUMMA_OUTPUT: outputControl.txt
SETTINGS_SUMMA_PARALLEL_EXE: summa_actors.exe
SETTINGS_SUMMA_PARALLEL_PATH: default
SETTINGS_SUMMA_PATH: default
SETTINGS_SUMMA_TIME_LIMIT: 01:00:00
SETTINGS_SUMMA_TRIALPARAMS: trialParams.nc
SETTINGS_SUMMA_TRIALPARAM_1: null
SETTINGS_SUMMA_TRIALPARAM_N: 0
SETTINGS_SUMMA_USE_PARALLEL_SUMMA: false
SIMULATIONS_PATH: default
SIM_REACH_ID: 123
SLOPE_AREA_EXPONENT: 2.0
SLOPE_AREA_THRESHOLD: 100.0
SMAP_PATH: default
SMAP_PRODUCT: SPL4SMGP
SNOTEL_PATH: /path/to/data/geospatial-data/SNOTEL
SNOTEL_STATION: null
SOILGRIDS_LAYER: wrb_0-5cm_mode
SOIL_CLASS_NAME: default
SOIL_CLASS_PATH: default
SOURCE_GEOFABRIC_BASINS_PATH: default
SOURCE_GEOFABRIC_RIVERS_PATH: default
SPINUP_PERIOD: 2020-01-01, 2020-01-01
STATION_ID: 05BB001
STREAMFLOW_DATA_PROVIDER: WSC
STREAMFLOW_PROCESSED_PATH: default
STREAMFLOW_RAW_NAME: default
STREAMFLOW_RAW_PATH: default
STREAM_THRESHOLD: 5000
SUMMA_DECISION_OPTIONS:
  LAI_method:
  - monTable
  alb_method:
  - conDecay
  astability:
  - louisinv
  bcLowrSoiH:
  - drainage
  bcLowrTdyn:
  - zeroFlux
  bcUpprSoiH:
  - liq_flux
  bcUpprTdyn:
  - nrg_flux
  canopyEmis:
  - difTrans
  canopySrad:
  - BeersLaw
  compaction:
  - anderson
  fDerivMeth:
  - analytic
  f_Richards:
  - mixdform
  groundwatr:
  - bigBuckt
  hc_profile:
  - constant
  num_method:
  - itertive
  snowIncept:
  - lightSnow
  snowLayers:
  - CLM_2010
  soilCatTbl:
  - ROSETTA
  soilStress:
  - NoahType
  spatial_gw:
  - localColumn
  stomResist:
  - BallBerry
  subRouting:
  - timeDlay
  thCondSnow:
  - smnv2000
  - jrdn1991
  thCondSoil:
  - funcSoilWet
  veg_traits:
  - Raupach_BLM1994
  vegeParTbl:
  - MODIFIED_IGBP_MODIS_NOAH
  windPrfile:
  - logBelowCanopy
SUMMA_EXE: summa_sundials.exe
SUMMA_INSTALL_PATH: default
SUPPLEMENT_FORCING: false
SWRMSIZE: 20
SYMFLUENCE_CODE_DIR: default
SYMFLUENCE_DATA_DIR: default
TAUDEM_DIR: default
TOOL_CACHE: /path/to/cache/dir
USE_DROP_ANALYSIS: false
USE_LOCAL_SCRATCH: false
USGS_STATION: '1674432'
