SYMFLUENCE_DATA_DIR: /Users/darrieythorsson/compHydro/code/SYMFLUENCE_data/
SYMFLUENCE_CODE_DIR: /Users/darrieythorsson/compHydro/code/SYMFLUENCE
DOMAIN_NAME: Bow_at_Banff_lumped_era5
POUR_POINT_COORDS: 51.1722/-115.5717
BOUNDING_BOX_COORDS: 51.76/-116.55/50.95/-115.5
DOMAIN_DEFINITION_METHOD: lumped
SUB_GRID_DISCRETIZATION: lumped
DOMAIN_DISCRETIZATION: GRUs
ROUTING_DELINEATION: lumped
GEOFABRIC_TYPE: TDX
STREAM_THRESHOLD: 10000
LUMPED_WATERSHED_METHOD: TauDEM
EXPERIMENT_TIME_START: 2002-01-01 01:00
EXPERIMENT_TIME_END: 2009-12-31 23:00
CALIBRATION_PERIOD: 2004-01-01, 2007-12-31
EVALUATION_PERIOD: 2008-01-01, 2009-12-31
SPINUP_PERIOD: 2002-01-01, 2003-12-31
FORCING_DATASET: ERA5
FORCING_VARIABLES: default
FORCING_MEASUREMENT_HEIGHT: 2
FORCING_TIME_STEP_SIZE: 3600
HYDROLOGICAL_MODEL: HBV
ROUTING_MODEL: none
HBV_TIMESTEP_HOURS: 24
HBV_WARMUP_DAYS: 365
HBV_BACKEND: jax
STREAMFLOW_DATA_PROVIDER: WSC
STATION_ID: 05BB001
DOWNLOAD_WSC_DATA: true
OPTIMIZATION_METHODS:
- iteration
OPTIMIZATION_METRIC: KGE
TARGET_METRIC: KGE
MPI_PROCESSES: 1
FORCE_RUN_ALL_STEPS: false
EXPERIMENT_ID: cal_ensemble_lbfgs_seed2042
RANDOM_SEED: 2042
ITERATIVE_OPTIMIZATION_ALGORITHM: LBFGS
NUMBER_OF_ITERATIONS: 500
HBV_SMOOTHING: true
HBV_SMOOTHING_FACTOR: 15.0
