SYMFLUENCE_DATA_DIR: /Users/darrieythorsson/compHydro/code/SYMFLUENCE_data
SYMFLUENCE_CODE_DIR: /Users/darrieythorsson/compHydro/code/SYMFLUENCE
NUM_PROCESSES: 1
DEBUG_MODE: false
LOG_LEVEL: INFO
LOG_TO_FILE: true
LOG_FORMAT: detailed
FORCE_RUN_ALL_STEPS: false
USE_LOCAL_SCRATCH: false
STOP_ON_ERROR: true
DOMAIN_NAME: Sagehen_Creek_near_Truckee
EXPERIMENT_ID: workshop_run_1
EXPERIMENT_TIME_START: 2016-01-01 01:00
EXPERIMENT_TIME_END: 2020-12-31 23:00
CALIBRATION_PERIOD: 2017-01-01, 2019-12-31
EVALUATION_PERIOD: 2020-01-01, 2020-12-31
SPINUP_PERIOD: 2016-01-01, 2016-12-31
DOMAIN_DEFINITION_METHOD: lumped
SUB_GRID_DISCRETIZATION: GRUs
SUBSET_FROM_GEOFABRIC: false
GRID_SOURCE: generate
NATIVE_GRID_DATASET: era5
GRID_CELL_SIZE: 1000.0
CLIP_GRID_TO_WATERSHED: true
POUR_POINT_COORDS: 39.4313/-120.2383
BOUNDING_BOX_COORDS: 39.48/-120.30/39.38/-120.18
ROUTING_DELINEATION: lumped
GEOFABRIC_TYPE: na
DELINEATION_METHOD: stream_threshold
CURVATURE_THRESHOLD: 0.0
MIN_SOURCE_THRESHOLD: 100
STREAM_THRESHOLD: 5000.0
SLOPE_AREA_THRESHOLD: 100.0
SLOPE_AREA_EXPONENT: 2.0
AREA_EXPONENT: 1.0
USE_DROP_ANALYSIS: false
DROP_ANALYSIS_MIN_THRESHOLD: 100
DROP_ANALYSIS_MAX_THRESHOLD: 10000
DROP_ANALYSIS_NUM_THRESHOLDS: 10
DROP_ANALYSIS_LOG_SPACING: true
LUMPED_WATERSHED_METHOD: TauDEM
CLEANUP_INTERMEDIATE_FILES: false
DELINEATE_COASTAL_WATERSHEDS: false
DELINEATE_BY_POURPOINT: true
MOVE_OUTLETS_MAX_DISTANCE: 200.0
MIN_GRU_SIZE: 0.0
MIN_HRU_SIZE: 0.0
ELEVATION_BAND_SIZE: 200.0
RADIATION_CLASS_NUMBER: 1
ASPECT_CLASS_NUMBER: 1
ASPECT_PATH: default
DATA_ACCESS: cloud
DOWNLOAD_DEM: true
DOWNLOAD_SOIL: true
DOWNLOAD_LAND_COVER: true
DEM_SOURCE: copernicus
LAND_CLASS_SOURCE: modis
LAND_CLASS_NAME: default
STREAMFLOW_DATA_PROVIDER: USGS
DOWNLOAD_USGS_DATA: true
DOWNLOAD_ISMN: false
BUILD_MODEL_READY_STORE: true
MODEL_READY_FORCING_STRATEGY: symlink
ELEV_CHUNK_SIZE: 10000
ELEV_TILE_TARGET: 50000
SOILGRIDS_LAYER: wrb_0-5cm_mode
SOILGRIDS_WCS_MAP: /map/wcs/soilgrids.map
SOILGRIDS_HS_CACHE_DIR: default
SOILGRIDS_HS_RESOURCE_ID: 1361509511e44adfba814f6950c6e742
MODIS_LANDCOVER_BASE_URL: https://zenodo.org/records/8367523/files
MODIS_LANDCOVER_CACHE_DIR: default
NLCD_COVERAGE_ID: NLCD_2019_Land_Cover_L48
FORCING_DATASET: AORC
FORCING_TIME_STEP_SIZE: 3600
FORCING_VARIABLES: default
FORCING_MEASUREMENT_HEIGHT: 10.0
APPLY_LAPSE_RATE: true
LAPSE_RATE: 0.0065
FORCING_SHAPE_LAT_NAME: lat
FORCING_SHAPE_LON_NAME: lon
PET_METHOD: oudin
SUPPLEMENT_FORCING: false
KEEP_RAW_FORCING: true
ERA5_ZARR_PATH: gcp-public-data-arco-era5/ar/full_37-1h-0p25deg-chunk-1.zarr-v3
ERA5_TIME_STEP_HOURS: 1
HYDROLOGICAL_MODEL: SUMMA
ROUTING_MODEL: none
GROUNDWATER_MODEL: MODFLOW
SUMMA_INSTALL_PATH: default
SUMMA_EXE: summa_sundials.exe
SETTINGS_SUMMA_PATH: default
SETTINGS_SUMMA_FILEMANAGER: fileManager.txt
SETTINGS_SUMMA_FORCING_LIST: forcingFileList.txt
SETTINGS_SUMMA_COLDSTATE: coldState.nc
SETTINGS_SUMMA_TRIALPARAMS: trialParams.nc
SETTINGS_SUMMA_ATTRIBUTES: attributes.nc
SETTINGS_SUMMA_OUTPUT: outputControl.txt
SETTINGS_SUMMA_BASIN_PARAMS_FILE: basinParamInfo.txt
SETTINGS_SUMMA_LOCAL_PARAMS_FILE: localParamInfo.txt
SETTINGS_SUMMA_CONNECT_HRUS: true
SETTINGS_SUMMA_TRIALPARAM_N: 0
SETTINGS_SUMMA_USE_PARALLEL_SUMMA: false
SETTINGS_SUMMA_CPUS_PER_TASK: 32
SETTINGS_SUMMA_TIME_LIMIT: 01:00:00
SETTINGS_SUMMA_MEM: 5G
SETTINGS_SUMMA_GRU_COUNT: 85
SETTINGS_SUMMA_GRU_PER_JOB: 5
SETTINGS_SUMMA_PARALLEL_PATH: default
SETTINGS_SUMMA_PARALLEL_EXE: summa_actors.exe
EXPERIMENT_OUTPUT_SUMMA: default
EXPERIMENT_LOG_SUMMA: default
PARAMS_TO_CALIBRATE: albedoMax,albedoMinWinter,newSnowDenMin,Fcapil,k_soil,theta_sat,critSoilWilting,theta_res,f_impede,tempCritRain,fieldCapacity
BASIN_PARAMS_TO_CALIBRATE: routingGammaShape,routingGammaScale
SUMMA_DECISION_OPTIONS: {}
CALIBRATE_DEPTH: false
SETTINGS_SUMMA_GLACIER_MODE: false
SETTINGS_SUMMA_GLACIER_ATTRIBUTES: attributes_glac.nc
SETTINGS_SUMMA_GLACIER_COLDSTATE: coldState_glac.nc
SUMMA_TIMEOUT: 7200
OPTIMIZATION_METHODS:
- iteration
OPTIMIZATION_TARGET: streamflow
CALIBRATION_VARIABLE: streamflow
CALIBRATION_TIMESTEP: hourly
ITERATIVE_OPTIMIZATION_ALGORITHM: DDS
OPTIMIZATION_METRIC: KGE
NUMBER_OF_ITERATIONS: 100
POPULATION_SIZE: 50
FINAL_EVALUATION_NUMERICAL_METHOD: ida
CLEANUP_PARALLEL_DIRS: true
GRADIENT_MODE: auto
GRADIENT_EPSILON: 0.0001
GRADIENT_CLIP_VALUE: 1.0
PARAMS_KEEP_TRIALS: false
ERROR_LOGGING_MODE: none
STOP_ON_MODEL_FAILURE: false
ERROR_LOG_DIR: error_logs
SWRMSIZE: 20
PSO_COGNITIVE_PARAM: 1.5
PSO_SOCIAL_PARAM: 1.5
PSO_INERTIA_WEIGHT: 0.7
PSO_INERTIA_REDUCTION_RATE: 0.99
INERTIA_SCHEDULE: LINEAR
DE_SCALING_FACTOR: 0.5
DE_CROSSOVER_RATE: 0.9
DDS_R: 0.2
ASYNC_DDS_POOL_SIZE: 10
ASYNC_DDS_BATCH_SIZE: 10
MAX_STAGNATION_BATCHES: 10
NUMBER_OF_COMPLEXES: 2
POINTS_PER_SUBCOMPLEX: 5
NUMBER_OF_EVOLUTION_STEPS: 20
EVOLUTION_STAGNATION: 5
PERCENT_CHANGE_THRESHOLD: 0.01
NSGA2_MULTI_TARGET: false
NSGA2_PRIMARY_TARGET: streamflow
NSGA2_SECONDARY_TARGET: gw_depth
NSGA2_PRIMARY_METRIC: KGE
NSGA2_SECONDARY_METRIC: KGE
NSGA2_CROSSOVER_RATE: 0.9
NSGA2_MUTATION_RATE: 0.1
NSGA2_ETA_C: 20
NSGA2_ETA_M: 20
MOEAD_MULTI_TARGET: false
MOEAD_PRIMARY_TARGET: streamflow
MOEAD_SECONDARY_TARGET: gw_depth
MOEAD_PRIMARY_METRIC: KGE
MOEAD_SECONDARY_METRIC: KGE
EMULATION_NUM_SAMPLES: 100
EMULATION_SEED: 22
EMULATION_SAMPLING_METHOD: lhs
EMULATION_PARALLEL_ENSEMBLE: false
EMULATION_MAX_PARALLEL_JOBS: 100
EMULATION_SKIP_MIZUROUTE: false
EMULATION_USE_ATTRIBUTES: false
EMULATION_MAX_ITERATIONS: 3
DOWNLOAD_WSC_DATA: false
STATION_ID: '10343500'
STREAMFLOW_RAW_PATH: default
STREAMFLOW_RAW_NAME: default
STREAMFLOW_PROCESSED_PATH: default
HYDAT_PATH: default
DOWNLOAD_SNOTEL: false
DOWNLOAD_FLUXNET: false
DOWNLOAD_USGS_GW: false
DOWNLOAD_SMAP: false
SMAP_PRODUCT: SPL4SMGP
SMAP_PATH: default
SMAP_USE_OPENDAP: false
SMAP_SURFACE_DEPTH_M: 0.05
SMAP_ROOTZONE_DEPTH_M: 1.0
ISMN_PATH: default
ISMN_API_BASE: https://ismn.earth/dataviewer
ISMN_METADATA_URL: https://ismn.earth/static/dataviewer/network_station_details.json
ISMN_MAX_STATIONS: 3
ISMN_TARGET_DEPTH_M: 0.05
ISMN_TEMPORAL_AGGREGATION: daily_mean
DOWNLOAD_GRACE: false
GRACE_PRODUCT: RL06
GRACE_PATH: default
GRACE_DATA_DIR: default
DOWNLOAD_MODIS_SNOW: false
MODIS_SNOW_PRODUCT: MOD10A1.061
MODIS_SNOW_PATH: default
MODIS_SNOW_DIR: default
MODIS_MIN_PIXELS: 100
MODIS_SCA_MERGE: true
MODIS_SCA_PRODUCTS:
- MOD10A1.061
- MYD10A1.061
MODIS_SCA_MERGE_STRATEGY: max
MODIS_SCA_CLOUD_FILTER: true
MODIS_SCA_MIN_VALID_RATIO: 0.1
MODIS_SCA_NORMALIZE: true
MODIS_SCA_USE_CATCHMENT_MASK: false
DOWNLOAD_MODIS_ET: false
MODIS_ET_PRODUCT: MOD16A2.061
MODIS_ET_PATH: default
MOD16_ET_DIR: default
ATTRIBUTES_DATA_DIR: default
ATTRIBUTES_SOILGRIDS_PATH: default
ATTRIBUTES_PELLETIER_PATH: default
ATTRIBUTES_MERIT_PATH: default
ATTRIBUTES_MODIS_PATH: default
ATTRIBUTES_GLCLU_PATH: default
ATTRIBUTES_FOREST_HEIGHT_PATH: default
ATTRIBUTES_WORLDCLIM_PATH: default
ATTRIBUTES_GLIM_PATH: default
ATTRIBUTES_GROUNDWATER_PATH: default
ATTRIBUTES_STREAMFLOW_PATH: default
ATTRIBUTES_GLWD_PATH: default
ATTRIBUTES_HYDROLAKES_PATH: default
ATTRIBUTES_OUTPUT_DIR: default
DOWNLOAD_SMHI_DATA: false
SMHI_PATH: default
DOWNLOAD_LAMAH_ICE_DATA: false
DOWNLOAD_GLACIER_DATA: false
GLACIER_PATH: default
GLACIER_SOURCE: RGI
HRU_GAUGE_MAPPING: {}
CATCHMENT_PATH: default
CATCHMENT_SHP_NAME: default
CATCHMENT_SHP_LAT: center_lat
CATCHMENT_SHP_LON: center_lon
CATCHMENT_SHP_AREA: HRU_area
CATCHMENT_SHP_ELEV: elev_mean
CATCHMENT_SHP_SLOPE: slope
CATCHMENT_SHP_HRUID: HRU_ID
CATCHMENT_SHP_GRUID: GRU_ID
RIVER_BASINS_PATH: default
RIVER_BASINS_NAME: default
RIVER_BASIN_SHP_RM_GRUID: GRU_ID
RIVER_BASIN_SHP_HRU_TO_SEG: gru_to_seg
RIVER_BASIN_SHP_AREA: GRU_area
RIVER_NETWORK_SHP_PATH: default
RIVER_NETWORK_SHP_NAME: default
RIVER_NETWORK_SHP_LENGTH: Length
RIVER_NETWORK_SHP_SEGID: LINKNO
RIVER_NETWORK_SHP_DOWNSEGID: DSLINKNO
RIVER_NETWORK_SHP_SLOPE: Slope
POUR_POINT_SHP_PATH: default
POUR_POINT_SHP_NAME: default
FORCING_PATH: default
OBSERVATIONS_PATH: default
SIMULATIONS_PATH: default
INTERSECT_SOIL_PATH: default
INTERSECT_SOIL_NAME: default
INTERSECT_ROUTING_PATH: default
INTERSECT_ROUTING_NAME: default
INTERSECT_DEM_PATH: default
INTERSECT_DEM_NAME: default
INTERSECT_LAND_PATH: default
INTERSECT_LAND_NAME: default
OUTPUT_BASINS_PATH: default
OUTPUT_RIVERS_PATH: default
DEM_PATH: default
DEM_NAME: default
SOURCE_GEOFABRIC_BASINS_PATH: default
SOURCE_GEOFABRIC_RIVERS_PATH: default
TAUDEM_DIR: default
OUTPUT_DIR: default
CATCHMENT_PLOT_DIR: default
SOIL_CLASS_PATH: default
SOIL_CLASS_NAME: default
LAND_CLASS_PATH: default
RADIATION_PATH: default
DATATOOL_PATH: default
GISTOOL_PATH: default
EASYMORE_CLIENT: easymore cli
DATATOOL_DATASET_ROOT: /path/to/meteorological-data/
GISTOOL_DATASET_ROOT: /path/to/geospatial-data/
TOOL_CACHE: /path/to/cache/dir
EASYMORE_CACHE: /path/to/cache/dir
EASYMORE_JOB_CONF: /path/to/esmr/job_config
CLUSTER_JSON: /path/to/cluster.json
GISTOOL_LIB_PATH: /path/to/r-env/
FEWS_WORK_DIR: .
FEWS_DATA_FORMAT: netcdf-cf
FEWS_DIAGNOSTICS_FILE: diag.xml
FEWS_MISSING_VALUE: -999.0
FEWS_AUTO_ID_MAP: true
COUPLING_MODE: sequential
MODFLOW_K: 5.0
MODFLOW_SY: 0.05
MODFLOW_TOP: 2300
MODFLOW_BOT: 2100
MODFLOW_DRAIN_ELEVATION: 2200
MODFLOW_DRAIN_CONDUCTANCE: 15000.0
MODFLOW_PARAMS_TO_CALIBRATE: K,SY,DRAIN_CONDUCTANCE
PARAMETER_BOUNDS:
  K:
  - 0.1
  - 50.0
  SY:
  - 0.005
  - 0.2
  fieldCapacity:
  - 0.1
  - 0.45
  critSoilWilting:
  - 0.01
  - 0.4
  albedoMinWinter:
  - 0.55
  - 0.85
  theta_res:
  - 0.01
  - 0.12
