SYMFLUENCE_CODE_DIR: /Users/darrieythorsson/compHydro/code/SYMFLUENCE
SYMFLUENCE_ROOT_CODE: /Users/darrieythorsson/compHydro/code/SYMFLUENCE
SYMFLUENCE_DATA_DIR: /Users/darrieythorsson/compHydro/code/SYMFLUENCE/SYMFLUENCE_data
DATA_ACCESS: cloud
DEM_SOURCE: copernicus
DOWNLOAD_SNOTEL: false
HYDROLOGICAL_MODEL: SUMMA
DOMAIN_DEFINITION_METHOD: storedPolygons
DOMAIN_DISCRETIZATION: singleHRU
DOMAIN_NAME: ellioaar_iceland
EXPERIMENT_ID: test_carra
EXPERIMENT_TIME_START: 2010-01-01 00:00
EXPERIMENT_TIME_END: 2010-01-01 02:00
FORCING_DATASET: CARRA
BOUNDING_BOX_COORDS: 64.13/-21.96/64.11/-21.94
POUR_POINT_COORDS: 64.12/-21.95
CARRA_DOMAIN: west_domain
_metadata:
  logged_at: '20251229_082701'
  symfluence_version: 1.0.0
  debug_mode: false
  python_version: 3.11.14
