SYMFLUENCE_DATA_DIR: /Users/darrieythorsson/compHydro/code/SYMFLUENCE_data/
SYMFLUENCE_CODE_DIR: /Users/darrieythorsson/compHydro/code/SYMFLUENCE
DOMAIN_NAME: Bow_at_Banff_lumped_era5
EXPERIMENT_ID: study_daily_ga_nosmooth_jax
EXPERIMENT_TIME_START: 2002-01-01 01:00
EXPERIMENT_TIME_END: 2009-12-31 23:00
CALIBRATION_PERIOD: 2004-01-01, 2007-12-31
EVALUATION_PERIOD: 2008-01-01, 2009-12-31
SPINUP_PERIOD: 2002-01-01, 2003-12-31
MPI_PROCESSES: 1
FORCE_RUN_ALL_STEPS: false
POUR_POINT_COORDS: 51.1722/-115.5717
BOUNDING_BOX_COORDS: 51.76/-116.55/50.95/-115.5
POUR_POINT_SHP_PATH: default
POUR_POINT_SHP_NAME: default
DOMAIN_DEFINITION_METHOD: lumped
ROUTING_DELINEATION: lumped
GEOFABRIC_TYPE: TDX
STREAM_THRESHOLD: 10000
LUMPED_WATERSHED_METHOD: TauDEM
CLEANUP_INTERMEDIATE_FILES: true
DELINEATE_BY_POURPOINT: true
MOVE_OUTLETS_MAX_DISTANCE: 200
MIN_GRU_SIZE: 1
DOMAIN_DISCRETIZATION: GRUs
SUB_GRID_DISCRETIZATION: lumped
COMBINED_DISCRETIZATION_METHODS: null
ELEVATION_BAND_SIZE: 200
MIN_HRU_SIZE: 4
RADIATION_CLASS_NUMBER: 5
ASPECT_CLASS_NUMBER: 8
ASPECT_PATH: default
CATCHMENT_PATH: default
CATCHMENT_SHP_NAME: default
CATCHMENT_SHP_LAT: center_lat
CATCHMENT_SHP_LON: center_lon
CATCHMENT_SHP_AREA: HRU_area
CATCHMENT_SHP_HRUID: HRU_ID
CATCHMENT_SHP_GRUID: GRU_ID
RIVER_BASINS_PATH: default
RIVER_BASINS_NAME: default
RIVER_BASIN_SHP_RM_GRUID: GRU_ID
RIVER_BASIN_SHP_HRU_TO_SEG: gru_to_seg
RIVER_BASIN_SHP_AREA: GRU_area
RIVER_NETWORK_SHP_PATH: default
RIVER_NETWORK_SHP_NAME: default
RIVER_NETWORK_SHP_LENGTH: Length
RIVER_NETWORK_SHP_SEGID: LINKNO
RIVER_NETWORK_SHP_DOWNSEGID: DSLINKNO
RIVER_NETWORK_SHP_SLOPE: Slope
OUTPUT_BASINS_PATH: default
OUTPUT_RIVERS_PATH: default
DEM_PATH: default
DEM_NAME: default
SOURCE_GEOFABRIC_BASINS_PATH: /Users/darrieythorsson/compHydro/data/CWARHM_data/domain_NorthAmerica/shapefiles/catchment/8020000010-basins.gpkg
SOURCE_GEOFABRIC_RIVERS_PATH: /Users/darrieythorsson/compHydro/data/CWARHM_data/domain_NorthAmerica/shapefiles/river_network/8020000010-streamnet.gpkg
TAUDEM_DIR: default
OUTPUT_DIR: default
CATCHMENT_PLOT_DIR: default
SOIL_CLASS_PATH: default
SOIL_CLASS_NAME: default
LAND_CLASS_PATH: default
LAND_CLASS_NAME: default
RADIATION_PATH: default
DATATOOL_PATH: default
GISTOOL_PATH: default
EASYMORE_CLIENT: easymore cli
DATATOOL_DATASET_ROOT: /work/comphyd_lab/data/meteorological-data/
DATATOOL_CACHE: /home/darri.eythorsson
TOOL_ACCOUNT: def-mclark
GISTOOL_DATASET_ROOT: /work/comphyd_lab/data/geospatial-data/
GISTOOL_LIB_PATH: /work/comphyd_lab/envs/r-env/
TOOL_CACHE: /home/darri.eythorsson/cache
EASYMORE_CACHE: /home/darri.eythorsson/easymore/
EASYMORE_JOB_CONF: installs/MAF/02_model_agnostic_component/easymore-job.slurm
CLUSTER_JSON: /work/comphyd_lab/users/darri/data/SYMFLUENCE_data/installs/datatool/etc/clusters/ucalgary-arc.json
FORCING_DATASET: ERA5
FORCING_VARIABLES: default
FORCING_MEASUREMENT_HEIGHT: 2
FORCING_TIME_STEP_SIZE: 3600
APPLY_LAPSE_RATE: true
LAPSE_RATE: 0.0065
FORCING_SHAPE_LAT_NAME: lat
FORCING_SHAPE_LON_NAME: lon
FORCING_PATH: default
SUPPLEMENT_FORCING: false
EM_EARTH_PRCP_DIR: /anvil/datasets/meteorological/EM-Earth/EM_Earth_v1/deterministic_hourly/prcp/NorthAmerica
EM_EARTH_TMEAN_DIR: /anvil/datasets/meteorological/EM-Earth/EM_Earth_v1/deterministic_hourly/tmean/NorthAmerica
INTERSECT_SOIL_PATH: default
INTERSECT_SOIL_NAME: catchment_with_soilclass.shp
INTERSECT_ROUTING_PATH: default
INTERSECT_ROUTING_NAME: catchment_with_routing_basins.shp
INTERSECT_DEM_PATH: default
INTERSECT_DEM_NAME: catchment_with_dem.shp
INTERSECT_LAND_PATH: default
INTERSECT_LAND_NAME: catchment_with_landclass.shp
HYDROLOGICAL_MODEL: HBV
ROUTING_MODEL: none
LSTM_TRAIN_THROUGH_ROUTING: true
HBV_TIMESTEP_HOURS: 24
HBV_WARMUP_DAYS: 365
HBV_BACKEND: jax
HBV_SMOOTHING: false
HBV_SMOOTHING_FACTOR: 15.0
PARAMS_TO_CALIBRATE: ''
BASIN_PARAMS_TO_CALIBRATE: ''
SETTINGS_SUMMA_CONNECT_HRUS: true
SETTINGS_SUMMA_TRIALPARAM_N: 0
SETTINGS_SUMMA_TRIALPARAM_1: null
DECISION_OPTIONS:
  snowIncept:
  - lightSnow
  - stickySnow
  compaction:
  - consettl
  - anderson
  snowLayers:
  - CLM_2010
  - jrdn1991
  alb_method:
  - conDecay
  - varDecay
  thCondSnow:
  - tyen1965
  - melr1977
  - jrdn1991
  - smnv2000
CALIBRATE_DEPTH: true
DEPTH_TOTAL_MULT_BOUNDS:
- 0.1
- 5.0
DEPTH_SHAPE_FACTOR_BOUNDS:
- 0.1
- 3.0
SETTINGS_SUMMA_PATH: default
SETTINGS_SUMMA_FILEMANAGER: fileManager.txt
SETTINGS_SUMMA_FORCING_LIST: forcingFileList.txt
SETTINGS_SUMMA_COLDSTATE: coldState.nc
SETTINGS_SUMMA_TRIALPARAMS: trialParams.nc
SETTINGS_SUMMA_ATTRIBUTES: attributes.nc
SETTINGS_SUMMA_OUTPUT: outputControl.txt
SETTINGS_SUMMA_BASIN_PARAMS_FILE: basinParamInfo.txt
SETTINGS_SUMMA_LOCAL_PARAMS_FILE: localParamInfo.txt
SUMMA_INSTALL_PATH: default
SUMMA_EXE: summa_sundials.exe
SETTINGS_SUMMA_USE_PARALLEL_SUMMA: false
SETTINGS_SUMMA_CPUS_PER_TASK: 32
SETTINGS_SUMMA_TIME_LIMIT: 01:00:00
SETTINGS_SUMMA_MEM: 5
SETTINGS_SUMMA_GRU_COUNT: 85
SETTINGS_SUMMA_GRU_PER_JOB: 5
SETTINGS_SUMMA_PARALLEL_PATH: default
SETTINGS_SUMMA_PARALLEL_EXE: summa.exe
SETTINGS_MIZU_WITHIN_BASIN: 0
SETTINGS_MIZU_ROUTING_DT: 3600
SETTINGS_MIZU_ROUTING_UNITS: m/s
SETTINGS_MIZU_ROUTING_VAR: averageRoutedRunoff
SETTINGS_MIZU_OUTPUT_FREQ: single
SETTINGS_MIZU_OUTPUT_VARS: 1
SETTINGS_MIZU_MAKE_OUTLET: n/a
SETTINGS_MIZU_NEEDS_REMAP: false
SETTINGS_MIZU_PATH: default
INSTALL_PATH_MIZUROUTE: default
EXE_NAME_MIZUROUTE: mizuroute.exe
SETTINGS_MIZU_TOPOLOGY: topology.nc
SETTINGS_MIZU_PARAMETERS: param.nml.default
SETTINGS_MIZU_CONTROL_FILE: mizuroute.control
SETTINGS_MIZU_REMAP: routing_remap.nc
EXPERIMENT_OUTPUT_SUMMA: default
EXPERIMENT_OUTPUT_MIZUROUTE: default
EXPERIMENT_LOG_MIZUROUTE: default
EXPERIMENT_LOG_SUMMA: default
SETTINGS_FUSE_FILEMANAGER: fm_catch.txt
FUSE_EXE: fuse.exe
GR_EXE: GR.r
FLASH_LOAD: false
FLASH_HIDDEN_SIZE: 128
FLASH_NUM_LAYERS: 3
FLASH_EPOCHS: 300
FLASH_BATCH_SIZE: 64
FLASH_LEARNING_RATE: 0.001
FLASH_LEARNING_PATIENCE: 30
FLASH_LOOKBACK: 700
FLASH_DROPOUT: 0.2
FLASH_L2_REGULARIZATION: 1e-6
FLASH_USE_ATTENTION: true
FLASH_USE_SNOW: false
LSTM_LOAD: false
LSTM_HIDDEN_SIZE: 128
LSTM_NUM_LAYERS: 3
LSTM_EPOCHS: 200
LSTM_BATCH_SIZE: 64
LSTM_LEARNING_RATE: 0.001
LSTM_LEARNING_PATIENCE: 30
LSTM_LOOKBACK: 30
LSTM_DROPOUT: 0.2
LSTM_L2_REGULARIZATION: 1e-6
LSTM_USE_ATTENTION: true
LSTM_USE_SNOW: false
LSTM_PARAMS_TO_CALIBRATE: null
LSTM_PARAMETER_BOUNDS:
  LSTM_LEARNING_RATE:
  - 0.0001
  - 0.01
  LSTM_DROPOUT:
  - 0.0
  - 0.5
GNN_HIDDEN_SIZE: 64
GNN_OUTPUT_SIZE: 32
GNN_EPOCHS: 100
GNN_BATCH_SIZE: 16
GNN_LEARNING_RATE: 0.005
GNN_DROPOUT: 0.2
GNN_USE_SNOW: false
GNN_LOAD: false
GNN_PARAMETER_BOUNDS:
  GNN_LEARNING_RATE:
  - 0.0001
  - 0.01
  GNN_DROPOUT:
  - 0.0
  - 0.5
SETTINGS_HYPE_PATH: default
SETTINGS_HYPE_CONTROL_FILE: info.txt
HYPE_INSTALL_PATH: default
HYPE_EXE: hype
HYPE_PARAMS_TO_CALIBRATE: ttmp,cmlt,cevp,lp,epotdist,rrcs1,rrcs2,rcgrw,rivvel,damp
SIM_REACH_ID: 228
SIMULATIONS_PATH: default
OBSERVATIONS_PATH: default
STREAMFLOW_DATA_PROVIDER: WSC
DOWNLOAD_USGS_DATA: true
DOWNLOAD_WSC_DATA: true
STATION_ID: 05BB001
STREAMFLOW_RAW_PATH: default
STREAMFLOW_RAW_NAME: default
STREAMFLOW_PROCESSED_PATH: default
HYDAT_PATH: /work/comphyd_lab/data/geospatial-data/hydat/Hydat.sqlite3
OPTIMIZATION_METHODS:
- iteration
EMULATION_NUM_SAMPLES: 100
EMULATION_SEED: 22
EMULATION_SAMPLING_METHOD: lhs
EMULATION_PARALLEL_ENSEMBLE: false
EMULATION_MAX_PARALLEL_JOBS: 100
EMULATION_SKIP_MIZUROUTE: false
EMULATION_USE_ATTRIBUTES: false
EMULATION_MAX_ITERATIONS': 3
ITERATIVE_OPTIMIZATION_ALGORITHM: GA
NUMBER_OF_ITERATIONS: 200
DDS_R: 0.2
POPULATION_SIZE: 20
OPTIMIZATION_METRIC: KGE
TARGET_METRIC: KGE
GLUE_THRESHOLD: -3.0
GLUE_SHAPING_FACTOR: 1.0
JFUSE_PARAM_BOUNDS:
  S1_max:
  - 10
  - 500
  S2_max:
  - 50
  - 2000
  ku:
  - 0.01
  - 1.0
  ki:
  - 0.001
  - 0.5
  ks:
  - 0.0001
  - 0.1
  n:
  - 1.0
  - 5.0
  b:
  - 0.5
  - 3.0
  Ac_max:
  - 0.1
  - 1.0
  f_rchr:
  - 0.0
  - 1.0
  T_rain:
  - -2.0
  - 4.0
  T_melt:
  - -2.0
  - 4.0
  MFMAX:
  - 1.0
  - 8.0
  MFMIN:
  - 0.5
  - 4.0
  smooth_frac:
  - 0.0
  - 1.0
ASYNC_DDS_POOL_SIZE: 10
ASYNC_DDS_BATCH_SIZE: 10
MAX_STAGNATION_BATCHES: 5
NUMBER_OF_COMPLEXES: 2
POINTS_PER_SUBCOMPLEX: 5
NUMBER_OF_EVOLUTION_STEPS: 20
EVOLUTION_STAGNATION: 5
PERCENT_CHANGE_THRESHOLD: 0.01
SWRMSIZE: 20
PSO_COGNITIVE_PARAM: 1.5
PSO_SOCIAL_PARAM: 1.5
PSO_INERTIA_WEIGHT: 0.7
PSO_INERTIA_REDUCTION_RATE: 0.99
DE_SCALING_FACTOR: 0.7
DE_CROSSOVER_RATE: 0.7
